#!/bin/sh

# adjust brightness of the OLPC XO backlight

usage()
{
    	echo "usage: ${0##*/} [up|down|high|low|<0-15>]"
	exit 1;
}

LEVEL=/sys/class/backlight/dcon-bl/brightness
MONOMODE=/sys/devices/platform/dcon/output

read curbright < $LEVEL

case $1 in
    "")	# no argument, just report current value
	    echo $curbright
	    exit
	    ;;
    high)
	    newbright=15
	    ;;
    low)	
	    newbright=0
	    ;;
    up)
	    newbright=$(($curbright + 1))
	    ;;
    down)
	    newbright=$(($curbright - 1))
	    ;;

    [0-9]|1[0-5])
	    newbright=$1
	    ;;
    *)
	    usage
	    ;;
esac

monochrome=$(( newbright == 0 ))

# POWEREVENTS=/var/run/powerevents
# echo "brightness $newbright $monochrome" > $POWEREVENTS

echo $newbright >$LEVEL
echo $monochrom >$MONOMODE


